services:
  - type: web
    name: casterly-rock-api
    runtime: python3
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_NAME
        value: simulacion_casterly_rock
      - key: TIMEZONE
        value: America/Bogota
      - key: API_TITLE
        value: Casterly Rock Simulation API
      - key: API_VERSION
        value: 1.0.0
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: https://frontend-castel.vercel.app
